export default {
  jsxSingleQuote: false,
  singleQuote: true,
  printWidth: 100,
  quoteProps: 'as-needed',
  proseWrap: 'preserve',
  arrowParens: 'always',
  trailingComma: 'es5',
  tabWidth: 2,
  semi: false,
  importOrder: [
    '<THIRD_PARTY_MODULES>',
    '^@/components/(.*)$',
    '^@/audits/(.*)$',
    '^@/core/(.*)$',
    '^@/lib/(.*)$',
    '^@/(.*)$',
    '^[./]',
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  tailwindStylesheet: './src/styles/globals.css',
  tailwindFunctions: ['cva', 'cn', 'clsx'],
  plugins: ['@trivago/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
}
